server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_SERVER:https://id.matejbucek.cz/}
          jwk-set-uri: ${OAUTH_KEYSET:https://id.matejbucek.cz/}
      client:
        provider:
          keycloak:
            issuer-uri: ${OAUTH_SERVER:https://id.matejbucek.cz/}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${OAUTH_ID:id}
            client-secret: ${OAUTH_SECRET:secret}
  cloud:
    gateway:
      routes:
      - id: admin
        uri: lb://PURKIADA-ADMIN
        predicates:
        - Path=/services/**,/sso/**
#      - id: asdf
#        uri: http://localhost:8083
#        predicates:
#        - Path=/sso/**
      - id: api
        uri: lb://PURKIADA-API
        predicates:
        - Path=/v1.0/**
      - id: client
        uri: http://${GW_FRONTEND}/
        predicates:
        - Path=/**
      x-forwarded:
        for-enabled: true
        proto-enabled: true
  application:
    name: PURKIADA-GATEWAY
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ADDR:localhost}:8761/eureka
    healthcheck:
      enabled: true
